package com.hana.exchange.stock.client;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;

public record OmniLensStockDetailResponse(
		String stockCode,
		String stockName,
		String stockNameEn,
		String market,
		String sector,
		BigDecimal currentPriceKrw,
		BigDecimal changeRate,
		long volume,
		String localCurrency,
		BigDecimal localCurrencyPrice,
		Instant marketDataTime,
		long foreignOwnedQuantity,
		BigDecimal foreignOwnershipRate,
		BigDecimal foreignLimitExhaustionRate,
		BigDecimal predictedForeignOwnershipRateMin,
		BigDecimal predictedForeignOwnershipRateMax,
		BigDecimal predictedForeignLimitExhaustionRateMin,
		BigDecimal predictedForeignLimitExhaustionRateMax,
		String foreignOwnershipPredictionConfidenceLevel,
		BigDecimal foreignOwnershipPredictionConfidenceScore,
		String foreignOwnershipPredictionModelVersion,
		LocalDate foreignOwnershipBaseDate,
		boolean viActive,
		boolean singlePriceTrading,
		String priceLimitState,
		boolean tradingHalted,
		boolean orderable,
		String source
) {
	public OmniLensStockDetailResponse(
			String stockCode,
			String stockName,
			String stockNameEn,
			String market,
			String sector,
			BigDecimal currentPriceKrw,
			BigDecimal changeRate,
			long volume,
			String localCurrency,
			BigDecimal localCurrencyPrice,
			Instant marketDataTime,
			long foreignOwnedQuantity,
			BigDecimal foreignOwnershipRate,
			BigDecimal foreignLimitExhaustionRate,
			LocalDate foreignOwnershipBaseDate,
			boolean viActive,
			boolean singlePriceTrading,
			String priceLimitState,
			boolean tradingHalted,
			boolean orderable,
			String source
	) {
		this(
				stockCode,
				stockName,
				stockNameEn,
				market,
				sector,
				currentPriceKrw,
				changeRate,
				volume,
				localCurrency,
				localCurrencyPrice,
				marketDataTime,
				foreignOwnedQuantity,
				foreignOwnershipRate,
				foreignLimitExhaustionRate,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				foreignOwnershipBaseDate,
				viActive,
				singlePriceTrading,
				priceLimitState,
				tradingHalted,
				orderable,
				source);
	}

	public OmniLensStockDetailResponse(
			String stockCode,
			String stockName,
			String stockNameEn,
			String market,
			String sector,
			BigDecimal currentPriceKrw,
			BigDecimal changeRate,
			long volume,
			String localCurrency,
			BigDecimal localCurrencyPrice,
			Instant marketDataTime,
			long foreignOwnedQuantity,
			BigDecimal foreignOwnershipRate,
			BigDecimal foreignLimitExhaustionRate,
			LocalDate foreignOwnershipBaseDate,
			boolean viActive,
			String priceLimitState,
			boolean tradingHalted,
			boolean orderable,
			String source
	) {
		this(
				stockCode,
				stockName,
				stockNameEn,
				market,
				sector,
				currentPriceKrw,
				changeRate,
				volume,
				localCurrency,
				localCurrencyPrice,
				marketDataTime,
				foreignOwnedQuantity,
				foreignOwnershipRate,
				foreignLimitExhaustionRate,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				foreignOwnershipBaseDate,
				viActive,
				false,
				priceLimitState,
				tradingHalted,
				orderable,
				source);
	}
}
