package com.hana.exchange.market.client;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;

public record OmniLensMarketQuote(
		String stockCode,
		String stockName,
		String stockNameEn,
		String market,
		BigDecimal currentPriceKrw,
		BigDecimal changeRate,
		long volume,
		BigDecimal executionPriceKrw,
		String marketSession,
		BigDecimal afterHoursPriceKrw,
		BigDecimal afterHoursLocalCurrencyPrice,
		BigDecimal afterHoursChangeRate,
		Long afterHoursVolume,
		Instant afterHoursMarketDataTime,
		String baseCurrency,
		BigDecimal localCurrencyPrice,
		String localCurrency,
		BigDecimal fxRate,
		Instant fxRateTime,
		String fxRateSource,
		boolean fxStale,
		long foreignOwnedQuantity,
		BigDecimal foreignOwnershipRate,
		BigDecimal foreignLimitExhaustionRate,
		LocalDate foreignOwnershipBaseDate,
		Instant marketDataTime,
		String source
) {
	public OmniLensMarketQuote(
			String stockCode,
			String stockName,
			String stockNameEn,
			String market,
			BigDecimal currentPriceKrw,
			BigDecimal changeRate,
			long volume,
			BigDecimal executionPriceKrw,
			String baseCurrency,
			BigDecimal localCurrencyPrice,
			String localCurrency,
			long foreignOwnedQuantity,
			BigDecimal foreignOwnershipRate,
			BigDecimal foreignLimitExhaustionRate,
			LocalDate foreignOwnershipBaseDate,
			Instant marketDataTime,
			String source) {
		this(
				stockCode,
				stockName,
				stockNameEn,
				market,
				currentPriceKrw,
				changeRate,
				volume,
				executionPriceKrw,
				"REGULAR",
				null,
				null,
				null,
				null,
				null,
				baseCurrency,
				localCurrencyPrice,
				localCurrency,
				null,
				marketDataTime,
				source,
				false,
				foreignOwnedQuantity,
				foreignOwnershipRate,
				foreignLimitExhaustionRate,
				foreignOwnershipBaseDate,
				marketDataTime,
				source);
	}

	public OmniLensMarketQuote(
			String stockCode,
			String stockName,
			String stockNameEn,
			String market,
			BigDecimal currentPriceKrw,
			BigDecimal changeRate,
			long volume,
			BigDecimal executionPriceKrw,
			String baseCurrency,
			BigDecimal localCurrencyPrice,
			String localCurrency,
			BigDecimal fxRate,
			Instant fxRateTime,
			String fxRateSource,
			boolean fxStale,
			long foreignOwnedQuantity,
			BigDecimal foreignOwnershipRate,
			BigDecimal foreignLimitExhaustionRate,
			LocalDate foreignOwnershipBaseDate,
			Instant marketDataTime,
			String source) {
		this(
				stockCode,
				stockName,
				stockNameEn,
				market,
				currentPriceKrw,
				changeRate,
				volume,
				executionPriceKrw,
				"REGULAR",
				null,
				null,
				null,
				null,
				null,
				baseCurrency,
				localCurrencyPrice,
				localCurrency,
				fxRate,
				fxRateTime,
				fxRateSource,
				fxStale,
				foreignOwnedQuantity,
				foreignOwnershipRate,
				foreignLimitExhaustionRate,
				foreignOwnershipBaseDate,
				marketDataTime,
				source);
	}
}
